robot:
  name: LittleCar2026
  target: default_car
  chassis_type: differential_drive

geometry:
  chassis:
    wheel_radius_m: 0.022
    track_width_m: 0.13
    half_track_m: 0.065

communication:
  uart:
    laser:
      logical_id: Laser
      handle: huart1
      baudrate: 115200
      tx_mode: dma
      rx_mode: idle_dma
      rx_buffer_size: 11
      rx_callback: Laser_OnUartRx


messages:
  High_TargetData:
    publisher: TargetDetector
    fields:
      target_distance_mm: int16_t
    subscribers:
      - Target_Data
  
  High_FeedbackData:
    publisher: FeedbackDetector
    fields:
      feedback_distance_mm: int16_t
      feedback_velocity_mmps: int16_t
    subscribers:
      - Feedback_Data

  Motor_OutData:
    publisher: MotorController
    fields:
      high_out: int16_t
    subscribers:
      - Motor_OutData

  LaserData:
    publisher: LaserDriver
    fields:
      distance_mm: int16_t
    subscribers:
      - High_LaserData

control:

  filters:
    high_distance_td:
      type: td
      r: 60.0
      h: 0.001
      initial_v1: 0.0
      initial_v2: 0.0

    high_velocity_td:
      type: td
      r: 50.0
      h: 0.001
      initial_v1: 0.0
      initial_v2: 0.0

    ude_filter_td:
      type: td
      r: 100.0
      h: 0.001
      initial_v1: 0.0
      initial_v2: 0.0

  feedforwards:
    gravity_forward:
      type: gravity
      k_gravity: 0.0
      phi_deg: 0.0

  observers:

  pid:
    high_distance_pid:
      type: pid
      kp: 0.0
      ki: 0.0
      kd: 0.0
      output_limit: 500
      integral_limit: 500
      integral_separation_threshold: 100.0
      R: 50.0
      T: 0.001

    high_velocity_pid:
      type: pid
      kp: 0.0
      ki: 0.0
      kd: 0.0
      output_limit: 300
      integral_limit: 500
      integral_separation_threshold: 100.0
      R: 50.0
      T: 0.001


hardware:
  motors:

  buttons:
    key1:
      pin: PG3
      mode: exti
      trigger: rising
      pull: none
      irq: EXTI3_IRQn
      active_low: true
    key2:
      pin: PG4
      mode: exti
      trigger: rising
      pull: none
      irq: EXTI4_IRQn
      active_low: true
    key3:
      pin: PG5
      mode: exti
      trigger: rising
      pull: none
      irq: EXTI9_5_IRQn
      active_low: true


  oled:
    type: ssd1306_i2c
    i2c_handle: hi2c1
    address: 0x3C
    width: 128
    height: 64



